### PR TITLE
Created triggerBSOD.

### PR DESCRIPTION
**Pull request by suegdu**
A function that triggers the "blue screen of death" can be called by importing `triggerBSOD.py` through the following:
```py
import triggerBSOD

triggerBSOD.Trigger()
```

Will crash any windows computer from usermode without any additional setup throwing it into BSOD.

### CODE REVIEW

**Comment by gumbobrot** [comment]
thank u so much man i probably got time today so i can fix everything and add missing features

**Comment by gumbobrot** [comment]
really helps me out

**Comment by suegdu** [comment]
@gumbobrot Reminding you

**Comment by gumbobrot** [comment]
ye

**Comment by gumbobrot** [comment]
btw msg me on cord if you wanna join the dev team again because im really lazy rn
`_gumbobrot`

**Comment by suegdu** [comment]
> btw msg me on cord if you wanna join the dev team again because im really lazy rn `_gumbobrot`

I don't use Discord anymore for these purposes.

**Comment by gumbobrot** [comment]
telegram then? its linked in our readme

**Comment by something-0001** [comment]
> telegram then? its linked in our readme

Depending on your needs, I can join the dev team.

**Comment by gumbobrot** [comment]
msg my tele

**Pull request merged**
