### PR TITLE
Added upgraded antivm

### PR DESCRIPTION
**Pull request by Minecraftkillir**
if you want to run the test yourself lmk that I can send you my test script

### CODE REVIEW

**Comment by gumbobr0t** [comment]
buddy what the heck is this, vms use like 500 different names and not only george or abby, i dont know where you scanned but defo not virustotal, also by just adding this to the source dir wont do anything because its nowhere executed & not even compiled into the main.py

**Comment by Minecraftkillir** [comment]
> buddy what the heck is this, vms use like 500 different names and not only george or abby, i dont know where you scanned but defo not virustotal, also by just adding this to the source dir wont do anything because its nowhere executed & not even compiled into the main.py

bro check your telegram

**Comment by gumbobr0t** [comment]
bro, it is still not going to be used in the main code because it is nowhere imported?? do you even know shit about py? and by avoiding 2 vms from 2000 but taking 5mb more space for the final stub is not a good deal

**Comment by Minecraftkillir** [comment]
> bro, it is still not going to be used in the main code because it is nowhere imported?? do you even know shit about py? and by avoiding 2 vms from 2000 but taking 5mb more space for the final stub is not a good deal

I didnt import it yet becuase I didnt want to mess things up

**Comment by gumbobr0t** [comment]
yeh cool but there are so many fucking different vm techniques and this is just shit

**Comment by Minecraftkillir** [comment]
> Member

true , yea I see why this is stupid , lets leave this then , ill just send you the updated antivm file , I added more prosses ID's to block

**Pull request closed without merging**
